#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

autoarandr --change &
xset r rate 240 30
xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
xwallpaper --zoom ~/dotfiles-public/wallpapers/stairs.jpg
xrdb -load -I$HOME/dotfiles-public/config/x11/Xresources.d ~/.Xresources & xrdbpid=$! # Use Xresources colors/settings on startup

autostart="nm-applet dunst xbanish"
for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

volapplet -icd &

dash ~/dotfiles-public/scripts/bar.sh &

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
